[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200

[functions]
  node_bundler = "esbuild"